[package]
name = "mongodb_model_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.79"
quote = { version = "1.0.37", features = [] }
proc-macro2 = "1.0"
darling = { version = "0.20.10", features = [] }
